#!/usr/bin/env sh

INPUT=$(echo $1 | sed "s/jq\/\([0-9]*\).*/\1.sample/")

CMD="jq -R -rn ${@:2} -f $1 $INPUT"

eval $CMD
nodemon -q -x "clear;echo ----------------------------; date; echo $CMD;echo ----------------------------; $CMD" -e jq
