#!/usr/bin/env sh

INPUT=$(echo $1 | sed "s/jq\/\([0-9]*\).*/\1.sample/")

echo "jq -R ${@:2} -f $1 $INPUT"
nodemon -q -x "clear;echo ----------------------------; date; echo ----------------------------; jq -R -r ${@:2} -f $1 $INPUT" -e jq
